#:\schema node_modules/wrangler/config-schema.json

name = "cf-comment-be"
main = "src/index.ts"
compatibility_date = "2025-05-22"

[[kv_namespaces]]
binding = "COMMENTS"
id = "dummy"
preview_id = "dummy"
