#:schema ./node_modules/wrangler/config-schema.json

name = "wonton-comment-be"
main = "src/index.ts"
compatibility_date = "2025-05-22"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "COMMENTS"
id = "<KV_COMMENTS_ID>"
preview_id = "<KV_COMMENTS_PREVIEW_ID>"

[[unsafe.bindings]]
name = "RATE_LIMITER_POST"
type = "ratelimit"
namespace_id = "1000"
simple = { limit = 2, period = 10 } # 2 requests per minute

[[unsafe.bindings]]
name = "RATE_LIMITER_GET"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 20, period = 10 } # 20 requests every 10 seconds

[vars]
MAX_PATH_LENGTH = 100
MAX_NAME_LENGTH = 25
MAX_MSG_LENGTH = 1000
